name: cinghy
description: A Flutter app for working with hledger files with OneDrive integration.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  path_provider: ^2.0.15
  intl: ^0.18.1
  uuid: ^3.0.7
  file_picker: ^5.3.2
  shared_preferences: ^2.2.0
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.1.12
  oauth2: ^2.0.2
  flutter_markdown: ^0.6.17
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/